import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Banner from '../components/Banner'
import SmallCard from '../components/SmallCard'
import MediumCard from '../components/MediumCard'
import LargeCard from '../components/LargeCard'
import Footer from '../components/Footer'

export default function Home({ exploreData,cardsData }) {
  return (
    <div className="bg-transparent bg-white">
      <Head>
        <title>My-AirB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Header />
     <Banner />

     <main className="max-w-7xl mx-auto px-12  sm:px-16">
      <section className="pt-2 ">
          <h2 className="text-gray-600 text-4xl font-semibold pb-5">Explore Nearby</h2>
          <div className="grid gap-0.5 p-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
          {/* Pull data from API endpoint */}
          {exploreData?.map((item) => (
            
            <SmallCard 
              key={item.img}
              item={item}
            />
            
          ))}
          </div>
      </section>
      <section className="text-gray-600 w-full">
        <h2 className="text-4xl font-semibold pb-5">Live Anywhere</h2>
        <div className=" flex p-3 space-x-3 overflow-scroll scroll-x-auto overflow-y-hidden scrollbar-thin">
        {/* Pull data from API endpoint */}
        {cardsData?.map((item) => (
            <MediumCard 
              key={item.img}
              item={item}
            />
          ))}
         </div>
      </section>
      <LargeCard 
        img='https://links.papareact.com/4cj'
        title='The Greatest Outdoors'
        description='Whishlists curated just for you.'
        buttonText='Get Inspired'
      />
      
     </main>
     <Footer />
    </div>
  )
}

export async function getStaticProps() {
  const exploreData = await fetch('https://www.jsonkeeper.com/b/4G1G')
  .then(
    (res) => res.json()
   ); 

  const cardsData = await fetch('https://www.jsonkeeper.com/b/VHHT')
  .then(
    (res) => res.json()
  );

  return {
    props:{
      exploreData,
      cardsData
    }
  }
}
